#pragma once
#include <glm/glm.hpp>
#include "transform.h"

class AABB {
public:

	AABB()
	{
		this->botRight = glm::vec2(0.5f, 0.5f);
		this->topLeft = glm::vec2(-0.5f, -0.5f);
	};

	AABB(const glm::vec2& _botRight, const glm::vec2& _topLeft)
	{
		this->botRight = _botRight;
		this->topLeft = _topLeft;
	};

	void init(const glm::vec2& _botRight, const glm::vec2& _topLeft, Transform _parentTransform) {
		this->botRight = _botRight;
		this->topLeft = _topLeft;
		this->parentTransform = _parentTransform;
		std::cout << "AABB initialized." << std::endl;
	};

	void update() {
		// Sync AABB position with parent transform position and rotation(autogenerated; possibly nonsense code)
		glm::vec3 parentPos = this->parentTransform.GetPos();
		glm::vec2 halfSize = (this->botRight - this->topLeft) * 0.5f;
		this->botRight = glm::vec2(parentPos.x, parentPos.y) + halfSize;
		this->topLeft = glm::vec2(parentPos.x, parentPos.y) - halfSize;
		this->transform.SetRot(this->parentTransform.GetRot());

	}

	void PointNormalTowardsPlayer() {
		// 2D plane, so align the normal with the position of the player so there is always a face towards them. no need for 3D

	}

private:
	glm::vec2 botRight;
	glm::vec2 topLeft;
	Transform parentTransform;
	Transform transform;
};

//// <summary> botRight and topLeft are 1:sqrt(2) ratio from GameObject::radius</summary>
/// https://danceswithcode.net/engineeringnotes/rotations_in_2d/rotations_in_2d.html